version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./config:/app/config


  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    image: postgres:15-alpine
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PGPASSWORD=mysecretpassword
    command: >
      sh -c "for f in /migrations/*_up.sql; do
        echo 'Applying migration: $$f'
        psql -h postgres -U postgres -d postgres -f $$f
      done"
    volumes:
      - ./migrations:/migrations